# Generated by Django 3.0.2 on 2020-01-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retete', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reteta',
            name='timp_executie',
            field=models.TimeField(default=0),
        ),
    ]
