# Generated by Django 3.0.2 on 2020-01-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retete', '0002_reteta_timp_executie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reteta',
            name='timp_executie',
            field=models.IntegerField(),
        ),
    ]
