# Generated by Django 3.0.2 on 2020-01-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retete', '0006_remove_reteta_timp_executie'),
    ]

    operations = [
        migrations.AddField(
            model_name='reteta',
            name='timp_executie',
            field=models.TextField(default=''),
        ),
    ]
