# Generated by Django 3.0.2 on 2020-01-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retete', '0010_reteta_timp_executie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reteta',
            name='timp_executie',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
